# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0
version = 1

[[annotations]]
path = [
 "mix.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
